// Code generated by "goconfig -field Env execx.Env|Dir string -option -output script_config_generated.go"; DO NOT EDIT.

package script

import "github.com/berquerant/execx"

type ConfigItem[T any] struct {
	modified     bool
	value        T
	defaultValue T
}

func (s *ConfigItem[T]) Set(value T) {
	s.modified = true
	s.value = value
}
func (s *ConfigItem[T]) Get() T {
	if s.modified {
		return s.value
	}
	return s.defaultValue
}
func (s *ConfigItem[T]) Default() T {
	return s.defaultValue
}
func (s *ConfigItem[T]) IsModified() bool {
	return s.modified
}
func NewConfigItem[T any](defaultValue T) *ConfigItem[T] {
	return &ConfigItem[T]{
		defaultValue: defaultValue,
	}
}

type Config struct {
	Env *ConfigItem[execx.Env]
	Dir *ConfigItem[string]
}
type ConfigBuilder struct {
	env execx.Env
	dir string
}

func (s *ConfigBuilder) Env(v execx.Env) *ConfigBuilder {
	s.env = v
	return s
}
func (s *ConfigBuilder) Dir(v string) *ConfigBuilder {
	s.dir = v
	return s
}
func (s *ConfigBuilder) Build() *Config {
	return &Config{
		Env: NewConfigItem(s.env),
		Dir: NewConfigItem(s.dir),
	}
}

func NewConfigBuilder() *ConfigBuilder { return &ConfigBuilder{} }
func (s *Config) Apply(opt ...ConfigOption) {
	for _, x := range opt {
		x(s)
	}
}

type ConfigOption func(*Config)

func WithEnv(v execx.Env) ConfigOption {
	return func(c *Config) {
		c.Env.Set(v)
	}
}
func WithDir(v string) ConfigOption {
	return func(c *Config) {
		c.Dir.Set(v)
	}
}
