apiVersion: v1
kind: Service
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-redis
  labels:
    app: redis
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
    {{- include "pneutrinoutil.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
{{- if .Values.pneutrinoutil.useKind }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-redis-expose
  labels:
    app: redis
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: redis
    {{- include "pneutrinoutil.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      nodePort: {{ .Values.pneutrinoutil.kind.ports.redis.container }}
      port: 6379
      targetPort: 6379
      name: redis-svc
{{- end }}
