apiVersion: v1
kind: Service
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-server
  labels:
    app: server
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  selector:
    app: server
    {{- include "pneutrinoutil.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 9101
      targetPort: 9101
      name: server-svc
{{- if .Values.pneutrinoutil.useKind }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-server-expose
  labels:
    app: server
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: server
    {{- include "pneutrinoutil.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      nodePort: {{ .Values.pneutrinoutil.kind.ports.server.container }}
      port: 9101
      targetPort: 9101
      name: server-svc
{{- end }}
