// Code generated by "goconfig -configOption Option -field Include []string|Exclude []string -option -output runner_config_generated.go"; DO NOT EDIT.

package task

type ConfigItem[T any] struct {
	modified     bool
	value        T
	defaultValue T
}

func (s *ConfigItem[T]) Set(value T) {
	s.modified = true
	s.value = value
}
func (s *ConfigItem[T]) Get() T {
	if s.modified {
		return s.value
	}
	return s.defaultValue
}
func (s *ConfigItem[T]) Default() T {
	return s.defaultValue
}
func (s *ConfigItem[T]) IsModified() bool {
	return s.modified
}
func NewConfigItem[T any](defaultValue T) *ConfigItem[T] {
	return &ConfigItem[T]{
		defaultValue: defaultValue,
	}
}

type Config struct {
	Include *ConfigItem[[]string]
	Exclude *ConfigItem[[]string]
}
type ConfigBuilder struct {
	include []string
	exclude []string
}

func (s *ConfigBuilder) Include(v []string) *ConfigBuilder {
	s.include = v
	return s
}
func (s *ConfigBuilder) Exclude(v []string) *ConfigBuilder {
	s.exclude = v
	return s
}
func (s *ConfigBuilder) Build() *Config {
	return &Config{
		Include: NewConfigItem(s.include),
		Exclude: NewConfigItem(s.exclude),
	}
}

func NewConfigBuilder() *ConfigBuilder { return &ConfigBuilder{} }
func (s *Config) Apply(opt ...Option) {
	for _, x := range opt {
		x(s)
	}
}

type Option func(*Config)

func WithInclude(v []string) Option {
	return func(c *Config) {
		c.Include.Set(v)
	}
}
func WithExclude(v []string) Option {
	return func(c *Config) {
		c.Exclude.Set(v)
	}
}
