services:
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    container_name: ui
    restart: unless-stopped
    ports:
      - "${UI_PORT}:3000"
    environment:
      SERVER_URI: "$CONTAINER_SERVER_URI"
    networks:
      pneutrinoutil:
