services:
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      # MYSQL_DATABASE: $MYSQL_DATABASE
      # MYSQL_USER: $MYSQL_USER
      # MYSQL_PASSWORD: $MYSQL_PASSWORD
