#!/bin/bash

target="$1"
shift

bin="./dist/NEUTRINO/bin"

if [ -z "$target" ] ; then
    echo "Require target:"
    find ./dist/NEUTRINO/bin -maxdepth 1 -type f -not -name "*.dylib" -print0 | xargs -0 basename
    exit 1
fi

export DYLD_LIBRARY_PATH=$PWD/dist/NEUTRINO/bin
"${bin}/${target}" "$@"
