name: Cluster Setup
description: Setup cluster
inputs:
  node_image:
    required: true
  version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install kind
      shell: bash
      run: |
        curl -Lso ./kind "https://github.com/kubernetes-sigs/kind/releases/download/${VERSION}/kind-linux-amd64"
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind version
      env:
        VERSION: '${{ inputs.version }}'
