name: Python Setup
description: Install Python
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
      with:
        enable-cache: true
    - name: Set up Python
      run: uv python install
    - name: Sync
      run: uv sync --locked --all-extras --dev
