apiVersion: v1
kind: Service
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-mysql
  labels:
    app: mysql
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  selector:
    app: mysql
    {{- include "pneutrinoutil.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql-svc
{{- if .Values.pneutrinoutil.useKind }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-mysql-expose
  labels:
    app: mysql
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: mysql
    {{- include "pneutrinoutil.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      nodePort: {{ .Values.pneutrinoutil.kind.ports.mysql.container }}
      port: 3306
      targetPort: 3306
      name: mysql-svc
{{- end }}
