name: Docker Setup
description: Setup docker daemon
runs:
  using: "composite"
  steps:
    - name: Set up Docker
      uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
      with:
        version: type=archive,channel=stable,version=v28.5.2
        daemon-config: |
          {
            "registry-mirrors": [
              "https://mirror.gcr.io"
            ]
          }
