apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-ui
  labels:
    app: ui
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      {{- include "pneutrinoutil.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ui
        {{- include "pneutrinoutil.labels" . | nindent 8 }}
      annotations:
        checksum/util: {{ include "pneutrinoutil.util" . | sha256sum }}
    spec:
      volumes:
        - name: script
          configMap:
            name: {{ include "pneutrinoutil.fullname" . }}-util
            defaultMode: 0755
            items:
              - key: retry.sh
                path: retry.sh
      initContainers:
        - name: wait-server
          image: "{{ .Values.images.curl.repository }}:{{ .Values.images.curl.tag }}"
          command:
            - /usr/local/bin/util/retry.sh
            - --
            - curl
            - -s
            - -I
            - http://{{ include "pneutrinoutil.fullname" . }}-server:9101/v1/health
          volumeMounts:
            - name: script
              mountPath: /usr/local/bin/util
              readOnly: true
      containers:
        - name: ui
          image: "{{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}"
          ports:
            - containerPort: 3000
              protocol: TCP
              name: ui-svc
          env:
            - name: SERVER_URI
              value: http://{{ include "pneutrinoutil.fullname" . }}-server:9101/v1
            - name: EXTERNAL_SERVER_URI
              value: {{ .Values.ui.externalServer }}/v1
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 3000
