apiVersion: v1
kind: Service
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-ui
  labels:
    app: ui
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  selector:
    app: ui
    {{- include "pneutrinoutil.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: ui-svc
{{- if .Values.pneutrinoutil.useKind }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pneutrinoutil.fullname" . }}-ui-expose
  labels:
    app: ui
    {{- include "pneutrinoutil.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: ui
    {{- include "pneutrinoutil.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      nodePort: {{ .Values.pneutrinoutil.kind.ports.ui.container }}
      port: 3000
      targetPort: 3000
      name: ui-svc
{{- end }}
