packages:
  - '.'
# for pnpm deploy
injectWorkspacePackages: true

allowBuilds:
  '@openapitools/openapi-generator-cli': true
  esbuild: true

packageExtensions:
  typescript-eslint:
    peerDependencies:
      typescript: "*"
  "@typescript-eslint/parser":
    peerDependencies:
      typescript: "*"
  "@typescript-eslint/eslint-plugin":
    peerDependencies:
      typescript: "*"

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
