version: '3'

tasks:
  default:
    deps:
      - dev
  install:
    cmds:
      - npm i
  build:
    deps:
      - install
    cmds:
      - npm run build
  build-image:
    cmds:
      - docker build -t pneutrinoutil-ui:dev .
  dev:
    desc: Start dev server
    deps:
      - install
    cmds:
      - npm run dev
  start:
    cmds:
      - npm run start
  lint:
    desc: Run linters
    deps:
      - typecheck
      - eslint
  typecheck:
    cmds:
      - npm run typecheck
  eslint:
    cmds:
      - npm run eslint
  swag:
    desc: Generate API
    cmds:
      - ./bin/swag.sh
