name: pnpm Setup
description: Install pnpm
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        package_json_file: ui/package.json
