name: pnpm Setup
description: Install pnpm
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        cache: true
        cache_dependency_path: ui/pnpm-lock.yaml
        package_json_file: ui/package.json
