name: Test

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  unit-test:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - name: Run Unit Test
        run: ./task test:unit

  e2e-test:
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - name: Run Integration Test
        run: ./task test:integration
        env:
          TEST_PARALLEL: "4"
      - name: Run E2E Test
        run: ./task test:e2e
        env:
          SKIP_BUILD: "true"
          SKIP_RELOAD_CLUSTER: "true"
          TEST_PARALLEL: "4"
